const {
  PUBLIC_STELLAR_NETWORK: STELLAR_NETWORK,
  PUBLIC_STELLAR_NETWORK_PASSPHRASE: HORIZON_NETWORK_PASSPHRASE,
  PUBLIC_STELLAR_HORIZON_URL: HORIZON_URL,
  PUBLIC_STELLAR_RPC_URL: SOROBAN_RPC_URL,
  PUBLIC_STELLAR_FRIENDBOT_URL: STELLAR_FRIENDBOT_URL,
  PUBLIC_CONTRACT_ADDRESS: CONTRACT_ADDRESS,
} = import.meta.env;

export {
  STELLAR_NETWORK,
  HORIZON_NETWORK_PASSPHRASE,
  HORIZON_URL,
  SOROBAN_RPC_URL,
  STELLAR_FRIENDBOT_URL,
  CONTRACT_ADDRESS,
};